
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-class-rp
  namespace: confluent
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "cfk/secrets-demo/rest-basic-txt"
        objectType: "secretsmanager"  
        objectAlias: basic.txt
      - objectName: "cfk/secrets-demo/rest-ccloud-jaas-api-access-conf"
        objectType: "secretsmanager"  
        objectAlias: ccloud-rp-access.jaas  
  secretObjects:                              # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects 
    - secretName: cp2ccloud-rest-users
      type: Opaque
      data:
       - objectName: basic.txt
         key: basic.txt 
       - objectName: ccloud-rp-access.jaas
         key: ccloud-rp-access.jaas    
