---
apiVersion: v1
kind: Secret
metadata:
  name: tls-zookeeper
  namespace: test-app-namespace
type: Opaque
data:
stringData:
  conjur-map: |-
    cacerts.pem: secrets/ca-certs/cacerts
    fullchain.pem: secrets/zookeeper/zookeeper-server
    privkey.pem: secrets/zookeeper/zookeeper-server-key

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-kafka
  namespace: test-app-namespace
type: Opaque
data:
stringData:
  conjur-map: |-
    cacerts.pem: secrets/ca-certs/cacerts 
    fullchain.pem: secrets/kafka/kafka-server
    privkey.pem: secrets/kafka/kafka-server-key

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-controlcenter
  namespace: test-app-namespace
type: Opaque
data:
stringData:
  conjur-map: |-
    cacerts.pem: secrets/ca-certs/cacerts
    fullchain.pem: secrets/controlcenter/controlcenter-server
    privkey.pem: secrets/controlcenter/controlcenter-server-key

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-connect
  namespace: test-app-namespace
type: Opaque
data:
stringData:
  conjur-map: |-
    cacerts.pem: secrets/ca-certs/cacerts
    fullchain.pem: secrets/connect/connect-server
    privkey.pem: secrets/connect/connect-server-key

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-schemaregistry
  namespace: test-app-namespace
type: Opaque
data:
stringData:
  conjur-map: |-
    cacerts.pem: secrets/ca-certs/cacerts
    fullchain.pem: secrets/schemaregistry/schemaregistry-server
    privkey.pem: secrets/schemaregistry/schemaregistry-server-key

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-kafkarestproxy
  namespace: test-app-namespace
type: Opaque
data:
stringData:
  conjur-map: |-
    cacerts.pem: secrets/ca-certs/cacerts
    fullchain.pem: secrets/kafkarestproxy/kafkarestproxy-server
    privkey.pem: secrets/kafkarestproxy/kafkarestproxy-server-key

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-ksqldb
  namespace: test-app-namespace
type: Opaque
data:
stringData:
  conjur-map: |-
    cacerts.pem: secrets/ca-certs/cacerts
    fullchain.pem: secrets/ksqldb/ksqldb-server
    privkey.pem: secrets/ksqldb/ksqldb-server-key

---