---
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: test-app-namespace
type: Opaque
data:
  DBName:   bXlhcHBEQg==
stringData:
  conjur-map: |-
    username: secrets/username
    password: secrets/password