---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: pageviews
  namespace: confluent
spec:
  class: "io.confluent.kafka.connect.datagen.DatagenConnector"
  taskMax: 4
  connectClusterRef:
    name: connect
  configs:
    kafka.topic: ${file:/mnt/secrets/datagen-az-vault-credential/datagen.txt:kafka.topic}
    quickstart: ${file:/mnt/secrets/datagen-az-vault-credential/datagen.txt:quickstart}
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter.schemas.enable: "false"
    max.interval: "100"
    iterations: ${file:/mnt/secrets/datagen-az-vault-credential/datagen.txt:iterations}