# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    #userAssignedIdentityID: 25b4525a-c06d-4386-b6d3-e9daf744f2eb  # Set the clientID of the user-assigned managed identity to use
    userAssignedIdentityID: ""  # Set to empty for the system 
    keyvaultName: amithazvaulttst        # Set to the name of your key vault
    objects:  |
      array:
        - |
          objectName: creds-zk-digest-sasl-users-json
          objectAlias: digest-users.json
          objectType: secret              # object types: secret, key, or cert
        - |
          objectName: kafka-zk-digest-creds-txt
          objectAlias: digest.txt
          objectType: secret              # object types: secret, key, or cert
        - |
          objectName: c3-basic-creds-users-txt
          objectAlias: basic.txt
          objectType: secret              # object types: secret, key, or cert         
        - |
          objectName: cfk-ca-cert-pem
          objectAlias: ca-server-cert.pem
          objectType: cert
        - |
          objectName: cfk-kafka-cert-pem
          objectAlias: kafka-server-cert.pem
          objectType: cert
        - |
          objectName: cfk-kafka-cert-pem
          objectAlias: kafka-priv-key-publ-cert.pem
          objectType: secret
        - |
          objectName: cfk-c3-cert-pem
          objectAlias: controlcenter-server-cert.pem
          objectType: cert
        - |
          objectName: cfk-c3-cert-pem
          objectAlias: controlcenter-priv-key-publ-cert.pem
          objectType: secret
        - |
          objectName: cfk-schemaregistry-cert-pem
          objectAlias: schemaregistry-server-cert.pem
          objectType: cert
        - |
          objectName: cfk-schemaregistry-cert-pem
          objectAlias: schemaregistry-priv-key-publ-cert.pem
          objectType: secret
        - |
          objectName: cfk-connect-cert-pem
          objectAlias: connect-server-cert.pem
          objectType: cert
        - |
          objectName: cfk-connect-cert-pem
          objectAlias: connect-priv-key-publ-cert.pem
          objectType: secret
        - |
          objectName: cfk-ksqldb-cert-pem
          objectAlias: ksqldb-server-cert.pem
          objectType: cert
        - |
          objectName: cfk-ksqldb-cert-pem
          objectAlias: ksqldb-priv-key-publ-cert.pem
          objectType: secret
    tenantId: 0893715b-959b-4906-a185-2789e1ead045                # The tenant ID of the key vault
  secretObjects:                              # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects 
    - secretName: credential
      type: Opaque
      data:
      - objectName: digest-users.json
        key: digest-users.json
      - objectName: digest.txt
        key: digest.txt
      - objectName: basic.txt
        key: basic.txt     
    - secretName: tls-kafka
      type: Opaque
      data:
      - objectName: kafka-priv-key-publ-cert.pem
        key: tls.key
      - objectName: kafka-server-cert.pem
        key: tls.crt
      - objectName: ca-server-cert.pem
        key: ca.crt
    - secretName: tls-controlcenter
      type: Opaque
      data:
      - objectName: controlcenter-priv-key-publ-cert.pem
        key: tls.key
      - objectName: controlcenter-server-cert.pem
        key: tls.crt
      - objectName: ca-server-cert.pem
        key: ca.crt
    - secretName: tls-schemaregistry
      type: Opaque
      data:
      - objectName: schemaregistry-priv-key-publ-cert.pem
        key: tls.key
      - objectName: schemaregistry-server-cert.pem
        key: tls.crt
      - objectName: ca-server-cert.pem
        key: ca.crt
    - secretName: tls-connect
      type: Opaque
      data:
      - objectName: connect-priv-key-publ-cert.pem
        key: tls.key
      - objectName: connect-server-cert.pem
        key: tls.crt
      - objectName: ca-server-cert.pem
        key: ca.crt
    - secretName: tls-ksqldb
      type: Opaque
      data:
      - objectName: ksqldb-priv-key-publ-cert.pem
        key: tls.key
      - objectName: ksqldb-server-cert.pem
        key: tls.crt
      - objectName: ca-server-cert.pem
        key: ca.crt

